Repository KusionStack/catalog, pull requests merged in 2024-01, with the labels that each got.

#45 fix: pull request template spelling issue
  .github/PULL_REQUEST_TEMPLATE.md
Labels: bug

#44 feat: update secret types for better developer experience
  models/samples/helloworld/base/base.k
  models/schema/v1/workload/common.k
  models/schema/v1/workload/network/port.k
  models/schema/v1/workload/secret/secret.k
Labels: enhancement

#46 feat: revert last commit for lower cognitive load
  models/samples/helloworld/base/base.k
  models/schema/v1/workload/common.k
  models/schema/v1/workload/secret/secret.k
Labels: enhancement

#48 fix: secret type data key mapping issue
  models/schema/v1/workload/secret/secret.k
Labels: bug

#49 chore: make the catalog a better repo
  README.md
  models/samples/hellocollaset/base/base.k
  models/samples/hellocollaset/prod/kcl.yaml
  models/samples/hellocollaset/prod/main.k
  models/samples/hellocollaset/prod/stack.yaml
  models/samples/hellocollaset/project.yaml
  models/samples/helloworld/base/base.k
  models/samples/helloworld/prod/kcl.yaml
  models/samples/helloworld/prod/main.k
  models/samples/helloworld/prod/stack.yaml
  models/samples/samplejob/base/base.k
  models/samples/samplejob/prod/kcl.yaml
  models/samples/samplejob/prod/main.k
  models/samples/samplejob/prod/stack.yaml
  models/samples/samplejob/project.yaml
  models/samples/wordpress/base/base.k
  models/samples/wordpress/prod/kcl.yaml
  models/samples/wordpress/prod/main.k
  models/samples/wordpress/prod/stack.yaml
  models/schema/v1/app_configuration.k
  models/schema/v1/monitoring/prometheus.k
  models/schema/v1/trait/opsrule.k
  models/schema/v1/workload/common.k
  models/schema/v1/workload/container/container.k
  models/schema/v1/workload/container/probe/probe.k
  models/schema/v1/workload/job.k
  models/schema/v1/workload/service.k
Labels: enhancement

#50 feat: update README.md add more info
  README.md
Labels: documentation

#51 refactor: updated monitoring schema to eliminate platform configs
  .gitignore
  models/samples/prometheus/base/base.k
  models/samples/prometheus/prod/kcl.yaml
  models/samples/prometheus/prod/main.k
  models/samples/prometheus/prod/stack.yaml
  models/samples/prometheus/project.yaml
  models/schema/v1/monitoring/prometheus.k
Labels: enhancement

#53 chore: update docstring with the correct example
  models/schema/v1/accessories/mysql.k
  models/schema/v1/accessories/postgres.k
  models/schema/v1/app_configuration.k
  models/schema/v1/monitoring/prometheus.k
  models/schema/v1/trait/opsrule.k
  models/schema/v1/workload/container/container.k
  models/schema/v1/workload/container/lifecycle/lifecycle.k
  models/schema/v1/workload/container/probe/probe.k
  models/schema/v1/workload/job.k
  models/schema/v1/workload/network/port.k
  models/schema/v1/workload/secret/secret.k
  models/schema/v1/workload/service.k
Labels: enhancement
